### ISSUE TITLE
How to move entire panel with draggable option enabled only on heading part?

### ISSUE THREAD

**Issue by sanket360** [cedvdb/ng2draggable#5]
I got your directive from your answer posted on http://stackoverflow.com/questions/36273791/how-to-implement-a-draggable-div-in-angular-2-using-rx

In my case, I am trying to move panel using panel heading with your ng2-draggable directive. Sample code below-

```
<div id="panel1" class="panel panel-primary resizable" >
  <div class="panel-heading" [ng2-draggable]=true>
    Handler for dragging
  </div>
  <div class="panel-body">
    Draggable and resizable content
  </div>
</div>
```

However, above code moves only panel heading and not entire panel. 

Could you please suggest how to move entire panel with draggable option enabled only on heading part?

**Comment by cedvdb** [comment]
@sanket360 I changed the name of the input you used. I feel like handle is more appropriate than target. https://github.com/cedvdb/ng2draggable#drag-element-with-child-element

**Comment by sanket360** [comment]
Thanks @cedvdb :+1:
