### ISSUE TITLE
forgot $event dependecy onMouseUp HostListener

### ISSUE THREAD

**Issue by morwn** [cedvdb/ng2draggable#9]
Hey,
please add $event dependecy on mouseUp event.

from:
@HostListener('document:mouseup')
to:
@HostListener('document:mouseup', [ '$event' ])

so we can use event parameter.

**Comment by cedvdb** [comment]
@morwn added. Watchout if you are using an earlier version than 1.3.0 and if you are somehow using an handler.  https://github.com/cedvdb/ng2draggable#drag-element-with-child-element
